"""empty message

Revision ID: 457e41bf01dc
Revises: 
Create Date: 2025-12-10 14:59:30.835739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e41bf01dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('language_id')

    # ### end Alembic commands ###
